# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 00:18
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('store_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('store_name', models.CharField(default='', max_length=30)),
                ('store_number', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('contact_person', models.CharField(default='', max_length=30)),
                ('contact_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number must be 10 digits long', regex='^\\+?1?\\d{10}$')])),
                ('secondary_contact_person', models.CharField(default='', max_length=30)),
                ('secondary_contact_number', models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile Number must be 10 digits long', regex='^\\+?1?\\d{10}$')])),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=30)),
                ('state', models.CharField(blank=True, default='', max_length=30)),
                ('country', models.CharField(blank=True, default='', max_length=30)),
                ('account_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='AssociateCategory',
            fields=[
                ('category_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssociateProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_id', models.CharField(default='', max_length=16)),
                ('store_id', models.CharField(default='', max_length=16)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('lumpsum', models.BooleanField(default=False)),
                ('l1_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('l2_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('franchise_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('charity_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AssociateCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_id', models.CharField(default='', max_length=16)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('staff_id', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('change_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=16)),
                ('itemname', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_address', models.CharField(blank=True, default='', max_length=100)),
                ('billing_address', models.CharField(blank=True, default='', max_length=100)),
                ('account_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tnc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_id', models.CharField(default='', max_length=16)),
                ('referral_id', models.CharField(blank=True, max_length=16)),
                ('customer_id', models.CharField(blank=True, max_length=16, null=True)),
                ('seller_id', models.CharField(default='', max_length=16)),
                ('bill_id', models.CharField(blank=True, max_length=16, null=True)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unlimited', models.NullBooleanField(default=False)),
                ('is_own_sale', models.BooleanField(default=True)),
                ('use_count', models.IntegerField(default=0)),
                ('close', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='', max_length=30)),
                ('landline_number', models.BigIntegerField(blank=True, default='', null=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=16)),
                ('itemname', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(default='', max_length=16)),
                ('user_id', models.CharField(default='', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remarks', models.CharField(default='', max_length=50)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_id', models.CharField(default='', max_length=16)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=13)),
                ('message', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recharge_id', models.CharField(default='', max_length=16)),
                ('customer_id', models.CharField(max_length=16)),
                ('operator_code', models.CharField(max_length=16)),
                ('amount', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=16)),
                ('child', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SalesCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('franchise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_id', models.CharField(default='X', max_length=16)),
                ('user_id', models.CharField(default='', max_length=16)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sp_id', models.CharField(default='X', max_length=16)),
                ('name', models.CharField(default='', max_length=30)),
                ('category', models.CharField(default='', max_length=30)),
                ('lumpsum', models.BooleanField(default=False)),
                ('l1_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('l2_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('franchise_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('staff_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('charity_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.ProductPrice')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sr_id', models.CharField(default='', max_length=16)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('franchise_id', models.CharField(default='', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_id', models.CharField(default='', max_length=16)),
                ('from_id', models.CharField(max_length=16)),
                ('to_id', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='pguser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pguser',
            name='country',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='pguser',
            name='district',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='pguser',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='pguser',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number must be 10 digits long', regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='pguser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pguser',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.StockProduct'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='franchise',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='stock_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.StockRequest'),
        ),
    ]
